version: '3.8'

services:
  db:
    image: postgres:13
    container_name: aegis_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-aegis_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: aegis_backend
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "flask db upgrade &&
             python -m app.infrastructure.seeding.seed_runner &&
             flask run --host=0.0.0.0"

volumes:
  postgres_data: