export enum UserRole {
  PATIENT = "PATIENT",
  DOCTOR = "DOCTOR",
  ADMIN = "ADMIN",
}

export enum MedicalReviewStatus {
  PENDING_MEDICAL_REVIEW = "PENDING_MEDICAL_REVIEW",
  APPROVED_BY_MEDICAL = "APPROVED_BY_MEDICAL",
  REJECTED_BY_MEDICAL = "REJECTED_BY_MEDICAL",
}

export enum PreAnalysisStatus {
  APTA = "APTA",
  CONDICIONAL = "CONDICIONAL",
  BLOQUEADA = "BLOQUEADA",
}

export enum PrescriptionStatus {
  ACTIVE = "ACTIVE",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
}

export enum OrderStatus {
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  PAID = "PAID",
  IN_PRODUCTION = "IN_PRODUCTION",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}

export enum InvoiceType {
  FARMACIA_PRODUTO = "FARMACIA_PRODUTO",
  PLATAFORMA_INTERMEDIACAO = "PLATAFORMA_INTERMEDIACAO",
}

export enum NotificationType {
  PRESCRIPTION_READY = "PRESCRIPTION_READY",
  ORDER_SHIPPED = "ORDER_SHIPPED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  GENERIC = "GENERIC",
}
